/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bine;

/**
 *
 * @author Ariel
 */
public class UserMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form UserMainWindow
     */
    public UserMainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontenerWarstw = new javax.swing.JLayeredPane();
        winaUzytkownikaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablicaWinUzytkownika = new javax.swing.JTable();
        dodajWinoUzytkownikaButton = new javax.swing.JButton();
        edytujWinoUzytkownikaButton = new javax.swing.JButton();
        usunWinoUzytkownikaButton = new javax.swing.JButton();
        dodajEdytujOpinieOWinieUseraButton = new javax.swing.JButton();
        szczegolyWinaUseraButton = new javax.swing.JButton();
        piwaUzytkownikaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablicaPiwUzytkownika = new javax.swing.JTable();
        szczegolyPiwaUseraButton = new javax.swing.JButton();
        usunPiwoUzytkownikaButton = new javax.swing.JButton();
        dodajEdytujOpinieOPiwieUseraButton = new javax.swing.JButton();
        dodajPiwoUzytkownikaButton = new javax.swing.JButton();
        edytujPiwoUzytkownikaButton = new javax.swing.JButton();
        winaGlobalnePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablicaWinGlobalnych = new javax.swing.JTable();
        szczegolyWinaGlobalnegoButton = new javax.swing.JButton();
        dodajEdytujOpinieOWinieGlobalnymButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        belkaMenu = new javax.swing.JMenuBar();
        plikMenu = new javax.swing.JMenu();
        wylogujMenuItem = new javax.swing.JMenuItem();
        zamknijMenuItem = new javax.swing.JMenuItem();
        edycjaMenu = new javax.swing.JMenu();
        dodajWinoMenuItem = new javax.swing.JMenuItem();
        dodajPiwoMenuItem = new javax.swing.JMenuItem();
        wyszukajMenuItem = new javax.swing.JMenuItem();
        wyswietlMenu = new javax.swing.JMenu();
        twojeWinaMenuItem = new javax.swing.JMenuItem();
        twojePiwaMenuItem = new javax.swing.JMenuItem();
        winaMenuItem = new javax.swing.JMenuItem();
        piwaMenuItem = new javax.swing.JMenuItem();
        oWinachMenuItem = new javax.swing.JMenuItem();
        oPiwachMenuItem = new javax.swing.JMenuItem();
        oProgramieMenu = new javax.swing.JMenu();
        pomocMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablicaWinUzytkownika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nazwa", "Rocznik", "Kraj pochodzenia", "Rodzaj wina", "Szczepy winogron"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablicaWinUzytkownika.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablicaWinUzytkownika);
        tablicaWinUzytkownika.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        dodajWinoUzytkownikaButton.setText("Dodaj nowe wino");

        edytujWinoUzytkownikaButton.setText("Edytuj");

        usunWinoUzytkownikaButton.setText("Usuń");

        dodajEdytujOpinieOWinieUseraButton.setText("Dodaj opinię");

        szczegolyWinaUseraButton.setText("Wyświetl szczegóły");

        javax.swing.GroupLayout winaUzytkownikaPanelLayout = new javax.swing.GroupLayout(winaUzytkownikaPanel);
        winaUzytkownikaPanel.setLayout(winaUzytkownikaPanelLayout);
        winaUzytkownikaPanelLayout.setHorizontalGroup(
            winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(winaUzytkownikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dodajWinoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dodajEdytujOpinieOWinieUseraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edytujWinoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(usunWinoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(szczegolyWinaUseraButton)
                .addContainerGap())
        );
        winaUzytkownikaPanelLayout.setVerticalGroup(
            winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winaUzytkownikaPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodajWinoUzytkownikaButton)
                    .addComponent(edytujWinoUzytkownikaButton)
                    .addComponent(szczegolyWinaUseraButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodajEdytujOpinieOWinieUseraButton)
                    .addComponent(usunWinoUzytkownikaButton))
                .addContainerGap())
        );

        winaUzytkownikaPanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(winaUzytkownikaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tablicaPiwUzytkownika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Browar", "Kraj pochodzenia", "Rodzaj piwa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablicaPiwUzytkownika);
        tablicaPiwUzytkownika.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        szczegolyPiwaUseraButton.setText("Wyświetl szczegóły");

        usunPiwoUzytkownikaButton.setText("Usuń");

        dodajEdytujOpinieOPiwieUseraButton.setText("Dodaj opinię");

        dodajPiwoUzytkownikaButton.setText("Dodaj nowe piwo");

        edytujPiwoUzytkownikaButton.setText("Edytuj");

        javax.swing.GroupLayout piwaUzytkownikaPanelLayout = new javax.swing.GroupLayout(piwaUzytkownikaPanel);
        piwaUzytkownikaPanel.setLayout(piwaUzytkownikaPanelLayout);
        piwaUzytkownikaPanelLayout.setHorizontalGroup(
            piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(piwaUzytkownikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dodajPiwoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dodajEdytujOpinieOPiwieUseraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edytujPiwoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(usunPiwoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(szczegolyPiwaUseraButton)
                .addContainerGap())
        );
        piwaUzytkownikaPanelLayout.setVerticalGroup(
            piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piwaUzytkownikaPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodajPiwoUzytkownikaButton)
                    .addComponent(edytujPiwoUzytkownikaButton)
                    .addComponent(szczegolyPiwaUseraButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodajEdytujOpinieOPiwieUseraButton)
                    .addComponent(usunPiwoUzytkownikaButton))
                .addContainerGap())
        );

        piwaUzytkownikaPanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(piwaUzytkownikaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tablicaWinGlobalnych.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nazwa", "Rocznik", "Kraj pochodzenia", "Rodzaj wina", "Szczepy winogron"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablicaWinGlobalnych);
        tablicaWinGlobalnych.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        szczegolyWinaGlobalnegoButton.setText("Wyświetl szczegóły");

        dodajEdytujOpinieOWinieGlobalnymButton.setText("Dodaj opinię");

        javax.swing.GroupLayout winaGlobalnePanelLayout = new javax.swing.GroupLayout(winaGlobalnePanel);
        winaGlobalnePanel.setLayout(winaGlobalnePanelLayout);
        winaGlobalnePanelLayout.setHorizontalGroup(
            winaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(winaGlobalnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dodajEdytujOpinieOWinieGlobalnymButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(szczegolyWinaGlobalnegoButton)
                .addContainerGap())
        );
        winaGlobalnePanelLayout.setVerticalGroup(
            winaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winaGlobalnePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(winaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szczegolyWinaGlobalnegoButton)
                    .addComponent(dodajEdytujOpinieOWinieGlobalnymButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        winaGlobalnePanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(winaGlobalnePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jPanel4.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jPanel5.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jPanel6.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        plikMenu.setText("Plik");

        wylogujMenuItem.setText("Wyloguj");
        wylogujMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wylogujMenuItemActionPerformed(evt);
            }
        });
        plikMenu.add(wylogujMenuItem);

        zamknijMenuItem.setText("Zamknij");
        zamknijMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijMenuItemActionPerformed(evt);
            }
        });
        plikMenu.add(zamknijMenuItem);

        belkaMenu.add(plikMenu);

        edycjaMenu.setText("Edycja");

        dodajWinoMenuItem.setText("Dodaj wino");
        edycjaMenu.add(dodajWinoMenuItem);

        dodajPiwoMenuItem.setText("Dodaj piwo");
        edycjaMenu.add(dodajPiwoMenuItem);

        wyszukajMenuItem.setText("Wyszukaj...");
        edycjaMenu.add(wyszukajMenuItem);

        belkaMenu.add(edycjaMenu);

        wyswietlMenu.setText("Wyświetl");

        twojeWinaMenuItem.setText("Twoje wina");
        wyswietlMenu.add(twojeWinaMenuItem);

        twojePiwaMenuItem.setText("Twoje piwa");
        wyswietlMenu.add(twojePiwaMenuItem);

        winaMenuItem.setText("Wina z bazy ogólnej");
        wyswietlMenu.add(winaMenuItem);

        piwaMenuItem.setText("Piwa z bazy ogólnej");
        wyswietlMenu.add(piwaMenuItem);

        oWinachMenuItem.setText("Opinie o winach");
        wyswietlMenu.add(oWinachMenuItem);

        oPiwachMenuItem.setText("Opinie o piwach");
        wyswietlMenu.add(oPiwachMenuItem);

        belkaMenu.add(wyswietlMenu);

        oProgramieMenu.setText("O programie");

        pomocMenuItem.setText("Pomoc");
        oProgramieMenu.add(pomocMenuItem);

        belkaMenu.add(oProgramieMenu);

        setJMenuBar(belkaMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kontenerWarstw, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kontenerWarstw, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zamknijMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_zamknijMenuItemActionPerformed

    private void wylogujMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wylogujMenuItemActionPerformed
        Logowanie logowanie = new Logowanie();
        logowanie.show();
        this.dispose();
    }//GEN-LAST:event_wylogujMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UserMainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar belkaMenu;
    private javax.swing.JButton dodajEdytujOpinieOPiwieUseraButton;
    private javax.swing.JButton dodajEdytujOpinieOWinieGlobalnymButton;
    private javax.swing.JButton dodajEdytujOpinieOWinieUseraButton;
    private javax.swing.JMenuItem dodajPiwoMenuItem;
    private javax.swing.JButton dodajPiwoUzytkownikaButton;
    private javax.swing.JMenuItem dodajWinoMenuItem;
    private javax.swing.JButton dodajWinoUzytkownikaButton;
    private javax.swing.JMenu edycjaMenu;
    private javax.swing.JButton edytujPiwoUzytkownikaButton;
    private javax.swing.JButton edytujWinoUzytkownikaButton;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLayeredPane kontenerWarstw;
    private javax.swing.JMenuItem oPiwachMenuItem;
    private javax.swing.JMenu oProgramieMenu;
    private javax.swing.JMenuItem oWinachMenuItem;
    private javax.swing.JMenuItem piwaMenuItem;
    private javax.swing.JPanel piwaUzytkownikaPanel;
    private javax.swing.JMenu plikMenu;
    private javax.swing.JMenuItem pomocMenuItem;
    private javax.swing.JButton szczegolyPiwaUseraButton;
    private javax.swing.JButton szczegolyWinaGlobalnegoButton;
    private javax.swing.JButton szczegolyWinaUseraButton;
    private javax.swing.JTable tablicaPiwUzytkownika;
    private javax.swing.JTable tablicaWinGlobalnych;
    private javax.swing.JTable tablicaWinUzytkownika;
    private javax.swing.JMenuItem twojePiwaMenuItem;
    private javax.swing.JMenuItem twojeWinaMenuItem;
    private javax.swing.JButton usunPiwoUzytkownikaButton;
    private javax.swing.JButton usunWinoUzytkownikaButton;
    private javax.swing.JPanel winaGlobalnePanel;
    private javax.swing.JMenuItem winaMenuItem;
    private javax.swing.JPanel winaUzytkownikaPanel;
    private javax.swing.JMenuItem wylogujMenuItem;
    private javax.swing.JMenu wyswietlMenu;
    private javax.swing.JMenuItem wyszukajMenuItem;
    private javax.swing.JMenuItem zamknijMenuItem;
    // End of variables declaration//GEN-END:variables
}
