/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bine;

/**
 *
 * @author Ariel
 */
public final class UserMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form UserMainWindow
     */
    public UserMainWindow() {
        initComponents();
        ukryjPanele();
        winaUzytkownikaPanel.setVisible(true);
        kontenerWarstw.moveToFront(winaUzytkownikaPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontenerWarstw = new javax.swing.JLayeredPane();
        winaUzytkownikaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablicaWinUzytkownika = new javax.swing.JTable();
        dodajWinoUzytkownikaButton = new javax.swing.JButton();
        edytujWinoUzytkownikaButton = new javax.swing.JButton();
        usunWinoUzytkownikaButton = new javax.swing.JButton();
        dodajEdytujOpinieOWinieUseraButton = new javax.swing.JButton();
        szczegolyWinaUseraButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        piwaUzytkownikaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablicaPiwUzytkownika = new javax.swing.JTable();
        szczegolyPiwaUseraButton = new javax.swing.JButton();
        usunPiwoUzytkownikaButton = new javax.swing.JButton();
        dodajEdytujOpinieOPiwieUseraButton = new javax.swing.JButton();
        dodajPiwoUzytkownikaButton = new javax.swing.JButton();
        edytujPiwoUzytkownikaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        winaGlobalnePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablicaWinGlobalnych = new javax.swing.JTable();
        szczegolyWinaGlobalnegoButton = new javax.swing.JButton();
        dodajEdytujOpinieOWinieGlobalnymButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        piwaGlobalnePanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablicaPiwGlobalnych = new javax.swing.JTable();
        szczegolyPiwaGlobalnegoButton = new javax.swing.JButton();
        dodajEdytujOpinieOPiwieGlobalnymButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        opinieOWinachPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablicaOpiniiOWinach = new javax.swing.JTable();
        szczegolyOpiniiOWinieButton = new javax.swing.JButton();
        usunOpinieOWinieButton = new javax.swing.JButton();
        edytujOpinieOWinieButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        opinieOPiwachPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablicaOpiniiOPiwach = new javax.swing.JTable();
        edytujOpinieOPiwieButton = new javax.swing.JButton();
        szczegolyOpiniiOPiwieButton = new javax.swing.JButton();
        usunOpinieOWinieButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        belkaMenu = new javax.swing.JMenuBar();
        plikMenu = new javax.swing.JMenu();
        wylogujMenuItem = new javax.swing.JMenuItem();
        zamknijMenuItem = new javax.swing.JMenuItem();
        edycjaMenu = new javax.swing.JMenu();
        dodajWinoMenuItem = new javax.swing.JMenuItem();
        dodajPiwoMenuItem = new javax.swing.JMenuItem();
        wyszukajMenuItem = new javax.swing.JMenuItem();
        wyswietlMenu = new javax.swing.JMenu();
        twojeWinaMenuItem = new javax.swing.JMenuItem();
        twojePiwaMenuItem = new javax.swing.JMenuItem();
        winaMenuItem = new javax.swing.JMenuItem();
        piwaMenuItem = new javax.swing.JMenuItem();
        oWinachMenuItem = new javax.swing.JMenuItem();
        oPiwachMenuItem = new javax.swing.JMenuItem();
        oProgramieMenu = new javax.swing.JMenu();
        pomocMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablicaWinUzytkownika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nazwa", "Rocznik", "Kraj pochodzenia", "Rodzaj wina", "Szczepy winogron"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablicaWinUzytkownika);

        dodajWinoUzytkownikaButton.setText("Dodaj nowe wino");
        dodajWinoUzytkownikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajWinoUzytkownikaButtonActionPerformed(evt);
            }
        });

        edytujWinoUzytkownikaButton.setText("Edytuj");
        edytujWinoUzytkownikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edytujWinoUzytkownikaButtonActionPerformed(evt);
            }
        });

        usunWinoUzytkownikaButton.setText("Usuń");

        dodajEdytujOpinieOWinieUseraButton.setText("Dodaj opinię");

        szczegolyWinaUseraButton.setText("Wyświetl szczegóły");
        szczegolyWinaUseraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szczegolyWinaUseraButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Lista twoich win");

        javax.swing.GroupLayout winaUzytkownikaPanelLayout = new javax.swing.GroupLayout(winaUzytkownikaPanel);
        winaUzytkownikaPanel.setLayout(winaUzytkownikaPanelLayout);
        winaUzytkownikaPanelLayout.setHorizontalGroup(
            winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(winaUzytkownikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winaUzytkownikaPanelLayout.createSequentialGroup()
                        .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dodajWinoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dodajEdytujOpinieOWinieUseraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edytujWinoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(usunWinoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(szczegolyWinaUseraButton))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        winaUzytkownikaPanelLayout.setVerticalGroup(
            winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winaUzytkownikaPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szczegolyWinaUseraButton)
                    .addComponent(edytujWinoUzytkownikaButton)
                    .addComponent(dodajWinoUzytkownikaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(winaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usunWinoUzytkownikaButton)
                    .addComponent(dodajEdytujOpinieOWinieUseraButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        winaUzytkownikaPanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(winaUzytkownikaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tablicaPiwUzytkownika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Browar", "Kraj pochodzenia", "Rodzaj piwa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablicaPiwUzytkownika);

        szczegolyPiwaUseraButton.setText("Wyświetl szczegóły");
        szczegolyPiwaUseraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szczegolyPiwaUseraButtonActionPerformed(evt);
            }
        });

        usunPiwoUzytkownikaButton.setText("Usuń");

        dodajEdytujOpinieOPiwieUseraButton.setText("Dodaj opinię");

        dodajPiwoUzytkownikaButton.setText("Dodaj nowe piwo");
        dodajPiwoUzytkownikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPiwoUzytkownikaButtonActionPerformed(evt);
            }
        });

        edytujPiwoUzytkownikaButton.setText("Edytuj");
        edytujPiwoUzytkownikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edytujPiwoUzytkownikaButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Lista twoich piw");

        javax.swing.GroupLayout piwaUzytkownikaPanelLayout = new javax.swing.GroupLayout(piwaUzytkownikaPanel);
        piwaUzytkownikaPanel.setLayout(piwaUzytkownikaPanelLayout);
        piwaUzytkownikaPanelLayout.setHorizontalGroup(
            piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(piwaUzytkownikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piwaUzytkownikaPanelLayout.createSequentialGroup()
                        .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dodajPiwoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dodajEdytujOpinieOPiwieUseraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edytujPiwoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(usunPiwoUzytkownikaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(szczegolyPiwaUseraButton))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        piwaUzytkownikaPanelLayout.setVerticalGroup(
            piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piwaUzytkownikaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szczegolyPiwaUseraButton)
                    .addComponent(edytujPiwoUzytkownikaButton)
                    .addComponent(dodajPiwoUzytkownikaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(piwaUzytkownikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usunPiwoUzytkownikaButton)
                    .addComponent(dodajEdytujOpinieOPiwieUseraButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        piwaUzytkownikaPanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(piwaUzytkownikaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tablicaWinGlobalnych.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nazwa", "Rocznik", "Kraj pochodzenia", "Rodzaj wina", "Szczepy winogron"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablicaWinGlobalnych);

        szczegolyWinaGlobalnegoButton.setText("Wyświetl szczegóły");
        szczegolyWinaGlobalnegoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szczegolyWinaGlobalnegoButtonActionPerformed(evt);
            }
        });

        dodajEdytujOpinieOWinieGlobalnymButton.setText("Dodaj opinię");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Lista win w globalnej bazie");

        javax.swing.GroupLayout winaGlobalnePanelLayout = new javax.swing.GroupLayout(winaGlobalnePanel);
        winaGlobalnePanel.setLayout(winaGlobalnePanelLayout);
        winaGlobalnePanelLayout.setHorizontalGroup(
            winaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(winaGlobalnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(winaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(winaGlobalnePanelLayout.createSequentialGroup()
                        .addComponent(dodajEdytujOpinieOWinieGlobalnymButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(szczegolyWinaGlobalnegoButton)))
                .addContainerGap())
        );
        winaGlobalnePanelLayout.setVerticalGroup(
            winaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winaGlobalnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(winaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodajEdytujOpinieOWinieGlobalnymButton)
                    .addComponent(szczegolyWinaGlobalnegoButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        winaGlobalnePanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(winaGlobalnePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tablicaPiwGlobalnych.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Browar", "Kraj pochodzenia", "Rodzaj piwa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablicaPiwGlobalnych);

        szczegolyPiwaGlobalnegoButton.setText("Wyświetl szczegóły");
        szczegolyPiwaGlobalnegoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szczegolyPiwaGlobalnegoButtonActionPerformed(evt);
            }
        });

        dodajEdytujOpinieOPiwieGlobalnymButton.setText("Dodaj opinię");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Lista piw w globalnej bazie");

        javax.swing.GroupLayout piwaGlobalnePanelLayout = new javax.swing.GroupLayout(piwaGlobalnePanel);
        piwaGlobalnePanel.setLayout(piwaGlobalnePanelLayout);
        piwaGlobalnePanelLayout.setHorizontalGroup(
            piwaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(piwaGlobalnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piwaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piwaGlobalnePanelLayout.createSequentialGroup()
                        .addComponent(dodajEdytujOpinieOPiwieGlobalnymButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(szczegolyPiwaGlobalnegoButton))
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        piwaGlobalnePanelLayout.setVerticalGroup(
            piwaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piwaGlobalnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(piwaGlobalnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szczegolyPiwaGlobalnegoButton)
                    .addComponent(dodajEdytujOpinieOPiwieGlobalnymButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        piwaGlobalnePanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(piwaGlobalnePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tablicaOpiniiOWinach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Kwasowość", "Taniczność", "Ocena"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablicaOpiniiOWinach);

        szczegolyOpiniiOWinieButton.setText("Wyświetl szczegóły");

        usunOpinieOWinieButton.setText("Usuń");

        edytujOpinieOWinieButton.setText("Edytuj");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Lista twoich opinii o winach");

        javax.swing.GroupLayout opinieOWinachPanelLayout = new javax.swing.GroupLayout(opinieOWinachPanel);
        opinieOWinachPanel.setLayout(opinieOWinachPanelLayout);
        opinieOWinachPanelLayout.setHorizontalGroup(
            opinieOWinachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(opinieOWinachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opinieOWinachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opinieOWinachPanelLayout.createSequentialGroup()
                        .addComponent(szczegolyOpiniiOWinieButton)
                        .addGap(18, 18, 18)
                        .addComponent(edytujOpinieOWinieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usunOpinieOWinieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        opinieOWinachPanelLayout.setVerticalGroup(
            opinieOWinachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opinieOWinachPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opinieOWinachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szczegolyOpiniiOWinieButton)
                    .addComponent(edytujOpinieOWinieButton)
                    .addComponent(usunOpinieOWinieButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        opinieOWinachPanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(opinieOWinachPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tablicaOpiniiOPiwach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nazwa", "Kwasowość", "Cierpkość", "Słodycz", "Ocena"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablicaOpiniiOPiwach);

        edytujOpinieOPiwieButton.setText("Edytuj");

        szczegolyOpiniiOPiwieButton.setText("Wyświetl szczegóły");

        usunOpinieOWinieButton1.setText("Usuń");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Lista twoich opinii o piwach");

        javax.swing.GroupLayout opinieOPiwachPanelLayout = new javax.swing.GroupLayout(opinieOPiwachPanel);
        opinieOPiwachPanel.setLayout(opinieOPiwachPanelLayout);
        opinieOPiwachPanelLayout.setHorizontalGroup(
            opinieOPiwachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(opinieOPiwachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opinieOPiwachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opinieOPiwachPanelLayout.createSequentialGroup()
                        .addComponent(szczegolyOpiniiOPiwieButton)
                        .addGap(18, 18, 18)
                        .addComponent(edytujOpinieOPiwieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usunOpinieOWinieButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        opinieOPiwachPanelLayout.setVerticalGroup(
            opinieOPiwachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opinieOPiwachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opinieOPiwachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usunOpinieOWinieButton1)
                    .addComponent(edytujOpinieOPiwieButton)
                    .addComponent(szczegolyOpiniiOPiwieButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        opinieOPiwachPanel.setBounds(0, 0, 705, 345);
        kontenerWarstw.add(opinieOPiwachPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        plikMenu.setText("Plik");

        wylogujMenuItem.setText("Wyloguj");
        wylogujMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wylogujMenuItemActionPerformed(evt);
            }
        });
        plikMenu.add(wylogujMenuItem);

        zamknijMenuItem.setText("Zamknij");
        zamknijMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijMenuItemActionPerformed(evt);
            }
        });
        plikMenu.add(zamknijMenuItem);

        belkaMenu.add(plikMenu);

        edycjaMenu.setText("Edycja");

        dodajWinoMenuItem.setText("Dodaj wino");
        dodajWinoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajWinoMenuItemActionPerformed(evt);
            }
        });
        edycjaMenu.add(dodajWinoMenuItem);

        dodajPiwoMenuItem.setText("Dodaj piwo");
        dodajPiwoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPiwoMenuItemActionPerformed(evt);
            }
        });
        edycjaMenu.add(dodajPiwoMenuItem);

        wyszukajMenuItem.setText("Wyszukaj...");
        edycjaMenu.add(wyszukajMenuItem);

        belkaMenu.add(edycjaMenu);

        wyswietlMenu.setText("Wyświetl");

        twojeWinaMenuItem.setText("Twoje wina");
        twojeWinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twojeWinaMenuItemActionPerformed(evt);
            }
        });
        wyswietlMenu.add(twojeWinaMenuItem);

        twojePiwaMenuItem.setText("Twoje piwa");
        twojePiwaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twojePiwaMenuItemActionPerformed(evt);
            }
        });
        wyswietlMenu.add(twojePiwaMenuItem);

        winaMenuItem.setText("Wina z bazy ogólnej");
        winaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winaMenuItemActionPerformed(evt);
            }
        });
        wyswietlMenu.add(winaMenuItem);

        piwaMenuItem.setText("Piwa z bazy ogólnej");
        piwaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piwaMenuItemActionPerformed(evt);
            }
        });
        wyswietlMenu.add(piwaMenuItem);

        oWinachMenuItem.setText("Opinie o winach");
        oWinachMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oWinachMenuItemActionPerformed(evt);
            }
        });
        wyswietlMenu.add(oWinachMenuItem);

        oPiwachMenuItem.setText("Opinie o piwach");
        oPiwachMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oPiwachMenuItemActionPerformed(evt);
            }
        });
        wyswietlMenu.add(oPiwachMenuItem);

        belkaMenu.add(wyswietlMenu);

        oProgramieMenu.setText("O programie");

        pomocMenuItem.setText("Pomoc");
        oProgramieMenu.add(pomocMenuItem);

        belkaMenu.add(oProgramieMenu);

        setJMenuBar(belkaMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kontenerWarstw, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kontenerWarstw, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zamknijMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_zamknijMenuItemActionPerformed

    private void wylogujMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wylogujMenuItemActionPerformed
        Logowanie logowanie = new Logowanie();
        logowanie.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wylogujMenuItemActionPerformed

    private void twojeWinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twojeWinaMenuItemActionPerformed
        ukryjPanele();
        winaUzytkownikaPanel.setVisible(true);
        kontenerWarstw.moveToFront(winaUzytkownikaPanel);
    }//GEN-LAST:event_twojeWinaMenuItemActionPerformed

    private void twojePiwaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twojePiwaMenuItemActionPerformed
        ukryjPanele();
        piwaUzytkownikaPanel.setVisible(true);
        kontenerWarstw.moveToFront(piwaUzytkownikaPanel);
    }//GEN-LAST:event_twojePiwaMenuItemActionPerformed

    private void winaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winaMenuItemActionPerformed
        ukryjPanele();
        winaGlobalnePanel.setVisible(true);
        kontenerWarstw.moveToFront(winaGlobalnePanel);
    }//GEN-LAST:event_winaMenuItemActionPerformed

    private void piwaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piwaMenuItemActionPerformed
        ukryjPanele();
        piwaGlobalnePanel.setVisible(true);
        kontenerWarstw.moveToFront(piwaGlobalnePanel);
    }//GEN-LAST:event_piwaMenuItemActionPerformed

    private void oWinachMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oWinachMenuItemActionPerformed
        ukryjPanele();
        opinieOWinachPanel.setVisible(true);
        kontenerWarstw.moveToFront(opinieOWinachPanel);
    }//GEN-LAST:event_oWinachMenuItemActionPerformed

    private void oPiwachMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oPiwachMenuItemActionPerformed
        ukryjPanele();
        opinieOPiwachPanel.setVisible(true);
        kontenerWarstw.moveToFront(opinieOPiwachPanel);
    }//GEN-LAST:event_oPiwachMenuItemActionPerformed

    private void dodajWinoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajWinoMenuItemActionPerformed
        DodawanieWina okno = new DodawanieWina(this, true, false);
        okno.setVisible(true);
    }//GEN-LAST:event_dodajWinoMenuItemActionPerformed

    private void dodajWinoUzytkownikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajWinoUzytkownikaButtonActionPerformed
        DodawanieWina okno = new DodawanieWina(this, true, false);
        okno.setVisible(true);
    }//GEN-LAST:event_dodajWinoUzytkownikaButtonActionPerformed

    private void dodajPiwoUzytkownikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPiwoUzytkownikaButtonActionPerformed
        DodawaniePiwa okno = new DodawaniePiwa(this, true, false);
        okno.setVisible(true);
    }//GEN-LAST:event_dodajPiwoUzytkownikaButtonActionPerformed

    private void dodajPiwoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPiwoMenuItemActionPerformed
        DodawaniePiwa okno = new DodawaniePiwa(this, true, false);
        okno.setVisible(true);
    }//GEN-LAST:event_dodajPiwoMenuItemActionPerformed

    private void edytujWinoUzytkownikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edytujWinoUzytkownikaButtonActionPerformed
        SzczegolyWina okno = new SzczegolyWina(this, true, true);
        okno.setVisible(true);
        //################DO MODYFIKACJII######################
    }//GEN-LAST:event_edytujWinoUzytkownikaButtonActionPerformed

    private void szczegolyWinaUseraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szczegolyWinaUseraButtonActionPerformed
        SzczegolyWina okno = new SzczegolyWina(this, true, false);
        okno.setVisible(true);
        //################DO MODYFIKACJII######################
    }//GEN-LAST:event_szczegolyWinaUseraButtonActionPerformed

    private void szczegolyWinaGlobalnegoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szczegolyWinaGlobalnegoButtonActionPerformed
        SzczegolyWina okno = new SzczegolyWina(this, true, false);
        okno.setVisible(true);
        //################DO MODYFIKACJII######################
    }//GEN-LAST:event_szczegolyWinaGlobalnegoButtonActionPerformed

    private void edytujPiwoUzytkownikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edytujPiwoUzytkownikaButtonActionPerformed
        SzczegolyPiwa okno = new SzczegolyPiwa(this, true, true);
        okno.setVisible(true);
    }//GEN-LAST:event_edytujPiwoUzytkownikaButtonActionPerformed

    private void szczegolyPiwaUseraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szczegolyPiwaUseraButtonActionPerformed
        SzczegolyPiwa okno = new SzczegolyPiwa(this, true, false);
        okno.setVisible(true);
    }//GEN-LAST:event_szczegolyPiwaUseraButtonActionPerformed

    private void szczegolyPiwaGlobalnegoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szczegolyPiwaGlobalnegoButtonActionPerformed
        SzczegolyPiwa okno = new SzczegolyPiwa(this, true, false);
        okno.setVisible(true);
    }//GEN-LAST:event_szczegolyPiwaGlobalnegoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar belkaMenu;
    private javax.swing.JButton dodajEdytujOpinieOPiwieGlobalnymButton;
    private javax.swing.JButton dodajEdytujOpinieOPiwieUseraButton;
    private javax.swing.JButton dodajEdytujOpinieOWinieGlobalnymButton;
    private javax.swing.JButton dodajEdytujOpinieOWinieUseraButton;
    private javax.swing.JMenuItem dodajPiwoMenuItem;
    private javax.swing.JButton dodajPiwoUzytkownikaButton;
    private javax.swing.JMenuItem dodajWinoMenuItem;
    private javax.swing.JButton dodajWinoUzytkownikaButton;
    private javax.swing.JMenu edycjaMenu;
    private javax.swing.JButton edytujOpinieOPiwieButton;
    private javax.swing.JButton edytujOpinieOWinieButton;
    private javax.swing.JButton edytujPiwoUzytkownikaButton;
    private javax.swing.JButton edytujWinoUzytkownikaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLayeredPane kontenerWarstw;
    private javax.swing.JMenuItem oPiwachMenuItem;
    private javax.swing.JMenu oProgramieMenu;
    private javax.swing.JMenuItem oWinachMenuItem;
    private javax.swing.JPanel opinieOPiwachPanel;
    private javax.swing.JPanel opinieOWinachPanel;
    private javax.swing.JPanel piwaGlobalnePanel;
    private javax.swing.JMenuItem piwaMenuItem;
    private javax.swing.JPanel piwaUzytkownikaPanel;
    private javax.swing.JMenu plikMenu;
    private javax.swing.JMenuItem pomocMenuItem;
    private javax.swing.JButton szczegolyOpiniiOPiwieButton;
    private javax.swing.JButton szczegolyOpiniiOWinieButton;
    private javax.swing.JButton szczegolyPiwaGlobalnegoButton;
    private javax.swing.JButton szczegolyPiwaUseraButton;
    private javax.swing.JButton szczegolyWinaGlobalnegoButton;
    private javax.swing.JButton szczegolyWinaUseraButton;
    private javax.swing.JTable tablicaOpiniiOPiwach;
    private javax.swing.JTable tablicaOpiniiOWinach;
    private javax.swing.JTable tablicaPiwGlobalnych;
    private javax.swing.JTable tablicaPiwUzytkownika;
    private javax.swing.JTable tablicaWinGlobalnych;
    private javax.swing.JTable tablicaWinUzytkownika;
    private javax.swing.JMenuItem twojePiwaMenuItem;
    private javax.swing.JMenuItem twojeWinaMenuItem;
    private javax.swing.JButton usunOpinieOWinieButton;
    private javax.swing.JButton usunOpinieOWinieButton1;
    private javax.swing.JButton usunPiwoUzytkownikaButton;
    private javax.swing.JButton usunWinoUzytkownikaButton;
    private javax.swing.JPanel winaGlobalnePanel;
    private javax.swing.JMenuItem winaMenuItem;
    private javax.swing.JPanel winaUzytkownikaPanel;
    private javax.swing.JMenuItem wylogujMenuItem;
    private javax.swing.JMenu wyswietlMenu;
    private javax.swing.JMenuItem wyszukajMenuItem;
    private javax.swing.JMenuItem zamknijMenuItem;
    // End of variables declaration//GEN-END:variables
    //###########Metody pomocnicze##############
    public void ukryjPanele()
    {
        piwaUzytkownikaPanel.setVisible(false);
        winaUzytkownikaPanel.setVisible(false);
        piwaGlobalnePanel.setVisible(false);
        winaGlobalnePanel.setVisible(false);
        opinieOPiwachPanel.setVisible(false);
        opinieOWinachPanel.setVisible(false);
    }
}
